[package]
name = "p1252_cells_with_odd_values_in_a_matrix"
version = "0.1.0"
authors = ["kanatapple <edamame1224@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
