[package]
name = "p1480_running_sum_of_1d_array"
version = "0.1.0"
authors = ["Yasunari Fujieda <yasunari.fujieda@dena.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
